CREATE TABLE MEMBERSHIP1(
        ID VARCHAR2(20),
        PWD VARCHAR2(20),
        PWDCHECK VARCHAR2(20),
        NAME VARCHAR2(20),
        NICKNAME VARCHAR2(20),
        TEL VARCHAR2(20),
        EMAIL VARCHAR2(20),
        GENDER VARCHAR2(20)
);


SELECT * FROM MEMBERSHIP1;